[project]
name = "stride"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "python-can (>=4.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"